apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-z8sl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-z8sl@sha256:b39f7812ee9aa40b4000cedf0b93b1542fe527f8471c81c2c3533c2bb03e0b38
        name: my-nodejs
        resources: {}
status: {}
